async function loadTingusData() {
    try {
        // Fetch the local JSON file generated by GitHub Actions
        const response = await fetch('data.json');
        const data = await response.json();

        // 1. Recent Game
        document.getElementById('recent-game').innerHTML = `
            <strong>Date:</strong> ${data.recent_game.date} <br>
            <strong>Matchup:</strong> ${data.recent_game.matchup} <br>
            <strong>Stats:</strong> ${data.recent_game.pts} PTS | ${data.recent_game.reb} REB | ${data.recent_game.blk} BLK
        `;

        // 2. Season Stats
        document.getElementById('season-stats').innerHTML = `
            <strong>${data.season.season_year} Season:</strong><br>
            ${data.season.pts} PPG | ${data.season.reb} RPG | ${data.season.blk} BPG <br>
            3PT%: ${data.season.fg3_pct}%
        `;

        // 3. Career Stats
        document.getElementById('career-stats').innerHTML = `
            <strong>Games Played:</strong> ${data.career.games_played} <br>
            <strong>Career Avg:</strong> ${data.career.pts_avg} PPG | ${data.career.reb_avg} RPG | ${data.career.blk_avg} BPG <br>
            <strong>Total Points:</strong> ${data.career.total_pts}
        `;
    } catch (error) {
        console.error("Error loading Tingus Pingus data:", error);
        document.getElementById('recent-game').innerText = "Failed to load data. The Knicks drafted him again.";
    }
}

loadTingusData();
